Resources:
  
  createCreditCardsqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:  ${file(resource/index.yml):card.createCreditCardsqs}


  createCreditCardsqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      PolicyDocument: 
        Statement:
          Effect: Allow
          Principal: '*'
          Action: 
            - SQS:*
          Resource: "*"
      Queues: 
        - {Ref: createCreditCardsqs}